# Generated by Django 5.0.3 on 2024-03-11 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_remove_candidate_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(default='select', on_delete=django.db.models.deletion.CASCADE, to='voting.position'),
        ),
    ]
